### ISSUE TITLE
private key in public repo

### ISSUE THREAD

**Issue by lucagrulla** [thomaschampagne/StravaPlus#2]
Hi,

Thanks for this useful extension.

Shouldn't you keep the signing private key...actually private, i.e. not accessible from the public repo?
https://developer.chrome.com/extensions/packaging

I guess you could now have to ask for a new key/pair, drop the existing one(it could have been already compromised) and potentially use a private repo for the packaging code and resoucres while keeping the actual extension code in a public repo.

cheers,
Luca

**Comment by thomaschampagne** [comment]
Hey,

Thanks Luca for your reply.

Actually i don't use it to sign the extension and create .crx file. It's a trap haha :)

But you right, i should don't keep that on my repo. i will delete it,

Thanks,

Cheers,

Tom
