### ISSUE TITLE
Heart rate zones chart tooltip: units and label in graph

### ISSUE THREAD

**Issue by j0nes2k** [thomaschampagne/StravaPlus#36]
When hovering over the heart rate zone chart, the name of the zone is shown as well as a number. It is not clear what this number is, I think it should be the number of minutes in this zone.

Suggestion: add label (like "minutes") 

Even better: make it customizable to display either number of minutes or percentage labels!

![bildschirmfoto 2015-03-08 um 15 50 11](https://cloud.githubusercontent.com/assets/1328479/6546195/e6434756-c5aa-11e4-8b92-8bda9045e717.png)

**Comment by thomaschampagne** [comment]
Minutes is now handled for 0.5.0
Example: **Z3 60% - 70%: 34 Minutes**

**Comment by j0nes2k** [comment]
Thanks!

**Comment by thomaschampagne** [comment]
Tooltip is now displayed like this **ZX Y% -Y% during hh:mm:ss**
