### ISSUE TITLE
Running cadence for both legs

### ISSUE THREAD

**Issue by gmucha** [thomaschampagne/StravaPlus#50]
Currently cadence shows as one leg only, unlike cycling cadence when running it's more common to use 2-sided cadence (ie. 180 SPM, not 90 SPm).

**Comment by thomaschampagne** [comment]
I'am cyclist not a runner :)

So no option for 1 or 2 legs?

I just need to multiply by 2 the cadence result? Do you have some example such as image, article to get a king of preview of this?

Thanks man ;)

**Comment by gmucha** [comment]
Here's how it looks like in Garmin Connect (Garmin watches also display it as 2 legs, not sure about Suunto / other brands. Generally they switched from 90 -> 180 type at some point in time) - but they export it as "single leg only" in TCX

![cadence] (http://i.imgur.com/WIy35MS.png)

Come to think about it, having it configurable would be nice.

**Comment by thomaschampagne** [comment]
- [ ] Optional two-leg settings checkbox in settings
