### ISSUE TITLE
Weird wording on QR code lightbox

### ISSUE THREAD

**Issue by paulmach** [thomaschampagne/StravaPlus#57]
"It can hard/long to find an activity on your smartphone..."

https://github.com/thomaschampagne/StravaPlus/blob/1b93a7958121f3ad6fc850b42a20cda0fbe942b1/hook/extension/js/modifiers/ActivityQRCodeDisplayModifier.js#L23

**Comment by KamensekD** [comment]
Please check https://github.com/thomaschampagne/StravaPlus/pull/65
