### ISSUE TITLE
Enable HR and other available stats for other types of workouts

### ISSUE THREAD

**Issue by KamensekD** [thomaschampagne/StravaPlus#62]
StravaPlus is great in showing extended statistics for Biking and Running (seems to also work for hiking and walking); It would be even greater/more complete if it could show at least HR (and/or other available data) statistics for any other activity.

For example I also row a lot on rowing ergometer with HR belt - there is no speed/distance, but HR and cadence data. Sometimes I also record HR when playing volleyball or workout with weights, others record their HR during skiing, swimming,...

Here are few of my sample activities for rowing and volleyball:
https://www.strava.com/activities/259856643
https://www.strava.com/activities/263956910
https://www.strava.com/activities/250675931   (activity "workout", because no volleyball in Strava)

If nothing else, we could see our TRIMP values, HRRavg and HR Zones distribution and possibly cadence, when available, for those kinds of activities, which would add a lot to completness of StravaPlus.

Next step could be improvement (based on TRIMP) of Stravas "Training/Fitness & Freshness" estimates of Fitness/Fatique/Form, which is great concept, but unforunately limited to biking only, so of no use to any multisport people...

**Comment by thomaschampagne** [comment]
Thanks for your time.

I already maked it in a previous issue #11
