### ISSUE TITLE
TRIMP/Hour

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/StravaPlus#73]

**Comment by KamensekD** [comment]
I'd suggest **TRIMP/hour** rather then TRIMP/km; it would be be **comparable between different types of activities**. I don't really see a point in TRIM/km even on cycling or running alone, cause flat kms are totally different story than hilly ones.

**Comment by thomaschampagne** [comment]
Indeed you right ! Thanks for your perspicacity
